name: CI/CD Pipeline

on:
  push:
    branches: [ "production" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.6.0]

    steps:
   #  - name : Truning Maintenance Mode on
   #    run: sudo touch /var/www/html/maintenance.flag

    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create .env file
      run: echo "${{secrets.ENV_VARIABLE}}" > .env
    - name: Load .env varables
      run: |
        export $(grep -v '^#' .env | xargs)
    - run: npm install -g pnpm
    - run: pnpm install --frozen-lockfile
    - name: Prisma Database Deploy
      run: npx prisma generate
    - run: npx prisma db push
    - name: Build
      run: pnpm run build
    - name: Change directory
      run: cd /home/ubuntu/gurukirpa/gurukirpaayurveda/gurukirpaayurveda
    - run: pm2 restart 9   

      



   #  - name: Install PM2
   #    run: npm install pm2 -g
   #  - run: pm2 restart 0 
   #  - name : Truning Maintenance Mode off
   #    run: sudo rm /var/www/html/maintenance.flag
   #  - run: sudo systemctl restart nginx

